### ISSUE TITLE
Improve date readability

### ISSUE THREAD

**Issue by ThomasBakker** [Nielssg/Tabby#1]
**Issue:**
Because the date is transparant, it isn't very nice to read. 

![image](https://user-images.githubusercontent.com/22427167/72829789-bdbcc680-3c7f-11ea-9620-d914784e570e.png)

**Suggested solution:**
Maybe make it less transparent

**Comment by Nielssg** [comment]
The given solution would indeed be better, but that is rather a bandage than an actual solution. The ultimate solution would be to determine, based on the image coloring behind the the full text, which color is the most dominant so we can decide if the text should be black or white. Feel free to implement it if you'd like 😄

**Comment by RemyyB** [comment]
This issue will be addressed in the next release ;)

**Comment by Nielssg** [comment]
@ThomasBakker @RemyyB A release with version 1.3 has been submitted to the Chrome Webstore and Firefox Addons, which will probably be live in the upcoming hours. Thanks for the feature request!

**Comment by ThomasBakker** [comment]
Thanks for the quick update! 😄
